### ISSUE TITLE
How to repruduce results on the VSPW dataset?

### ISSUE THREAD

**Issue by Z-singer** [openseg-group/RankSeg#4]
Thanks for your great work! 
I'm trying to reproduce the results of Mask2former+RankSeg on the VSPW dataset (Swin-B as the backbone) according to your config file, but the mIoU indicators I can get is only 52%. Do you have any good suggestions for reproducing the results in this paper?

**Comment by PkuRainBow** [comment]
@hardyho

**Comment by hardyho** [comment]
Hi,

The Mask2Former-video experiments are finetuning experiments based on Mask2Former-image checkpoints (following the setting of the Youtube-VIS dataset in the Mask2Former paper).
You should try to use the checkpoint downloaded from the Mask2Former GitHub repo(https://dl.fbaipublicfiles.com/maskformer/mask2former/coco/instance/maskformer2_swin_base_IN21k_384_bs16_50ep/model_final_83d103.pkl), and put it in pretrained_weights/ folder and see if it works. The config should be correct.
 
The result may have some variance and you may have to run it several times and get the average number. Usually, the difference is within 1% mIoU.
 
Please tell me if there are any further questions.

**Comment by Z-singer** [comment]
Thanks for your sugesstion, I tried the pretrained _swin-base_ checkpoint downloaded from the Mask2Former GitHub, and the best mIoU I can get now is 58.9%. 
By the way, I found that the best result(60.1%) of VSPW dataset reported in your paper is trained based on the **Swin-L** backbone, while the best result shown in the GitHub Model Zoos is based on the **Swin-B** backbone. Do I need to use Swin-L as the backbone to obtain the best result？
